function [fitresult, gof] = createFit(mir223x, mir223spot)
%CREATEFIT(MIR223X,MIR223SPOT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : mir223x
%      Y Output: mir223spot
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jun-2021 13:09:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( mir223x, mir223spot );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [54.5744210385384 0.0030858379336484];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'mir223spot vs. mir223x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel mir223x
ylabel mir223spot
grid on


