function [fitresult, gof] = LangmuirFit(t_assoc, assoc, concentration, scaleMax)
%CREATEFIT(T_ASSOC,ASSOC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t_assoc
%      Y Output: assoc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jun-2020 11:43:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t_assoc, assoc );

% Set up fittype and options.
ft = fittype( 'a*(kon*c/(kon*c+koff))*(1-exp(-(kon*c+koff)*(x)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.8 concentration 5e-06 1000];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.StartPoint = [1 0.990401275095381 5e-06 5000];
opts.Upper = [scaleMax concentration 1e-4 100000];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'assoc vs. t_assoc', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel t_assoc
% ylabel assoc
% grid on


